backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - file: "content/site.json"
        label: "General"
        name: "general"
        fields:
          - { name: "name", label: "Restaurant Name", widget: "string" }
          - { name: "tagline", label: "Tagline", widget: "string" }
          - { name: "address", label: "Address", widget: "string" }
          - { name: "phone", label: "Phone", widget: "string" }
          - { name: "email", label: "Email", widget: "string" }
          - name: "hours"
            label: "Hours"
            widget: "object"
            fields:
              - { name: "lunch",  label: "Lunch",  widget: "string" }
              - { name: "dinner", label: "Dinner", widget: "string" }
              - { name: "notes",  label: "Notes",  widget: "string", required: false }
          - name: "sellingPoints"
            label: "Selling Points"
            widget: "list"
          - name: "social"
            label: "Social"
            widget: "object"
            fields:
              - { name: "instagram", label: "Instagram URL", widget: "string", required: false }

  - name: "menu"
    label: "Menu"
    file: "content/menu.json"
    fields:
      - { name: "tabs", label: "Tabs", widget: "list" }
      - name: "dishes"
        label: "Dishes"
        widget: "list"
        fields:
          - { name: "tab",  label: "Tab",  widget: "string" }
          - { name: "name", label: "Name", widget: "string" }
          - { name: "desc", label: "Description", widget: "text" }
          - { name: "tags", label: "Tags", widget: "list", required: false }

  - name: "gallery"
    label: "Gallery"
    file: "content/gallery.json"
    fields:
      - name: "images"
        label: "Images"
        widget: "list"
        fields:
          - { name: "src", label: "Image URL", widget: "string" }
          - { name: "alt", label: "Alt Text", widget: "string" }
